In [1]:
import pandas as pd
from datetime import datetime

In [2]:
csv_file = "./AMZN_joop.csv"
csv_GOOG = "./GOOG_joop.csv"
csv_JNJ = "./JNJ_joop.csv"
csv_PFE = "./PFE_joop.csv"
csv_TSLA = "./TSLA_joop.csv"
csv_MRNA = "./MRNA_joop.csv"

In [3]:
AMZN_data_df = pd.read_csv(csv_file)
GOOG_data_df = pd.read_csv(csv_GOOG)
JNJ_data_df = pd.read_csv(csv_JNJ)
PFE_data_df = pd.read_csv(csv_PFE)
TSLA_data_df = pd.read_csv(csv_TSLA)
MRNA_data_df = pd.read_csv(csv_MRNA)
MRNA_data_df.head()

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1429231603981688837,1429231603981688837,2021-08-21 16:59:02 Pacific Daylight Time,2021-08-21,16:59:02,-700,2994201737,cashk3tchum,nobody,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1429230960130678787,1429230960130678787,2021-08-21 16:56:29 Pacific Daylight Time,2021-08-21,16:56:29,-700,1195022670967914496,anchieiji2,エイジ🌸,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,1429230420319604739,1429167651415265288,2021-08-21 16:54:20 Pacific Daylight Time,2021-08-21,16:54:20,-700,1425854198759911429,luego85781348,Luego Trades 📉,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'toadwatcher1', 'name': 'toad...",NaN,NaN,NaN,NaN
3,1429228273591017483,1429225543279562760,2021-08-21 16:45:48 Pacific Daylight Time,2021-08-21,16:45:48,-700,1095463879033917441,zavalalol1,Zavala,NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'KeepIt1K4L', 'name': 'Keep I...",NaN,NaN,NaN,NaN
4,1429224733522944001,1429224733522944001,2021-08-21 16:31:44 Pacific Daylight Time,2021-08-21,16:31:44,-700,1218208096889208834,jpatrades,John Trades,NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN

In [4]:
new_AMZN_data_df = AMZN_data_df[['date',
                                   'time',
                                   'username',
                                   'tweet',
                                   'hashtags',
                                   'cashtags']].copy()

new_GOOG_data_df = GOOG_data_df[['date',
                                   'time',
                                   'username',
                                   'tweet',
                                   'hashtags',
                                   'cashtags']].copy()

new_JNJ_data_df = JNJ_data_df[['date',
                                   'time',
                                   'username',
                                   'tweet',
                                   'hashtags',
                                   'cashtags']].copy()

new_PFE_data_df = PFE_data_df[['date',
                                   'time',
                                   'username',
                                   'tweet',
                                   'hashtags',
                                   'cashtags']].copy()

new_TSLA_data_df = TSLA_data_df[['date',
                                   'time',
                                   'username',
                                   'tweet',
                                   'hashtags',
                                   'cashtags']].copy()

new_MRNA_data_df = MRNA_data_df[['date',
                                   'time',
                                   'username',
                                   'tweet',
                                   'hashtags',
                                   'cashtags']].copy()
new_MRNA_data_df.head()

,date,time,username,tweet,hashtags,cashtags
0,2021-08-21,16:59:02,cashk3tchum,$pfe &amp; $mrna on Monday,[],"['pfe', 'mrna']"
1,2021-08-21,16:56:29,anchieiji2,$BNTX $MRNA おはようございます😃今日もNHKで23:30から放送されますね。こ...,[],"['bntx', 'mrna']"
2,2021-08-21,16:54:20,luego85781348,@toadwatcher1 @StockMKTNewz $MRNA is overvalue...,[],['mrna']
3,2021-08-21,16:45:48,zavalalol1,@KeepIt1K4L Pump and dumped $MRNA LMAO,[],['mrna']
4,2021-08-21,16:31:44,jpatrades,Me to all the bears still calling for the top ...,[],"['ttd', 'rblx', 'amc', 'ddd', 'mvst', 'gme', '..."

In [5]:
new_AMZN_data_df.dtypes

date        object
time        object
username    object
tweet       object
hashtags    object
cashtags    object
dtype: object

In [6]:
new_AMZN_data_df['date'] = pd.to_datetime(new_AMZN_data_df.date)
new_GOOG_data_df['date'] = pd.to_datetime(new_GOOG_data_df.date)
new_JNJ_data_df['date'] = pd.to_datetime(new_JNJ_data_df.date)
new_PFE_data_df['date'] = pd.to_datetime(new_PFE_data_df.date)
new_TSLA_data_df['date'] = pd.to_datetime(new_TSLA_data_df.date)
new_MRNA_data_df['date'] = pd.to_datetime(new_MRNA_data_df.date)
new_AMZN_data_df

,date,time,username,tweet,hashtags,cashtags
0,2021-08-21,16:53:00,hectorcannabis,@VirginTraderGal Check out Amazon history sinc...,[],"['amzn', 'amzn', 'hmbl']"
1,2021-08-21,16:51:35,stoxdox,"@MikeZaccardi $AMZN P/S of 3.7x, however, Amaz...",[],"['amzn', 'wmt', 'fdx', 'kr']"
2,2021-08-21,16:51:06,davesf1235,@WOLF_Financial $ADBE $AAPL $AMZN $NVDA. Held...,[],"['adbe', 'aapl', 'amzn', 'nvda', 'nvda']"
3,2021-08-21,16:45:20,askwarrenbuffet,$WPMLF Will Confirm That Reverse Merger Discus...,[],"['wpmlf', 'tsla', 'kgc', 'dnr', 'axp', 'acrl',..."
4,2021-08-21,16:42:12,finapse_24_7,[Last 2 Hours] Stocks trending among elite #f...,"['fintwit', 'investing', 'stocks', 'wallstreet...","['tsla', 'fulc', 'ocgn', 'roku', 'amzn', 'sos']"
...,...,...,...,...,...,...
4386,2021-08-17,17:11:31,ruedashraf,@ProblemSniper $amzn had a nice hammer on dail...,[],['amzn']
4387,2021-08-17,17:10:31,askwarrenbuffet,$YRIV CEO to reveal new JV with $AMZN as early...,[],"['yriv', 'amzn', 'lazy', 'slrc', 'mye', 'decxf..."
4388,2021-08-17,17:04:10,nerdhodl,The comparison of $AMZN and $HMBL really have ...,[],"['amzn', 'hmbl', 'amzn', 'hmbl']"
4389,2021-08-17,17:00:37,workhardpays0ff,@michaelpatron0 Buy $amzn calls,[],['amzn']
4390,2021-08-17,17:00:00,limitlesst1,Trade Ideas 📝 $PTON 115c over 113 Targets: 1...,[],"['pton', 'unh', 'aapl', 'tsla', 'amzn', 'shop'..."

In [7]:
new_AMZN_data_df.dtypes

date        datetime64[ns]
time                object
username            object
tweet               object
hashtags            object
cashtags            object
dtype: object

In [8]:
new_AMZN_data_df = new_AMZN_data_df[(new_AMZN_data_df['date'] > '2021-08-17') & (new_AMZN_data_df['date'] <= '2021-08-20')]
new_GOOG_data_df = new_GOOG_data_df[(new_GOOG_data_df['date'] > '2021-08-17') & (new_GOOG_data_df['date'] <= '2021-08-20')]
new_JNJ_data_df = new_JNJ_data_df[(new_JNJ_data_df['date'] > '2021-08-17') & (new_JNJ_data_df['date'] <= '2021-08-20')]
new_PFE_data_df = new_PFE_data_df[(new_PFE_data_df['date'] > '2021-08-17') & (new_PFE_data_df['date'] <= '2021-08-20')]
new_TSLA_data_df = new_TSLA_data_df[(new_TSLA_data_df['date'] > '2021-08-17') & (new_TSLA_data_df['date'] <= '2021-08-20')]
new_MRNA_data_df = new_MRNA_data_df[(new_MRNA_data_df['date'] > '2021-08-17') & (new_MRNA_data_df['date'] <= '2021-08-20')]

In [9]:
new_AMZN_data_df

,date,time,username,tweet,hashtags,cashtags
382,2021-08-20,23:59:02,luthejp,2021年8月6日に行われた $BIGC (ビッグコマース)の四半期決算説明会和訳・翻訳をn...,[],"['bigc', 'shop', 'amzn']"
383,2021-08-20,23:54:01,shortvolumes,Short sale volume (not short interest) for $ET...,[],"['etsy', 'amzn', 'ebay']"
384,2021-08-20,23:44:27,ishikawatrader,【21年8月】＃資産総額 ＃セゾン投信 ＃ひふみ投信 ＃賢明なる投資家 ＃懸命なる投資家 ＃...,"['資産総額', 'セゾン投信', 'ひふみ投信', '賢明なる投資家', '懸命なる投資家...","['msft', 'shop', 'amzn', 'tsla', 'okta', 'sq',..."
385,2021-08-20,23:34:06,tradediary10,@tastytraderMike Just short $AMZN when its gre...,[],"['amzn', 'qqq']"
386,2021-08-20,23:29:50,mytldr,@ultimatejingle What bull market? - Fellow $A...,[],['amzn']
...,...,...,...,...,...,...
4217,2021-08-18,01:06:17,newsfilterio,Jeff Bezos' Blue Origin Loses Lead Engineer Wo...,[],"['amzn', 'tsla']"
4218,2021-08-18,00:56:00,prolifictraders,“A stock broker is one who invests other peopl...,['investing'],"['aapl', 'msft', 'goog', 'googl', 'amzn', 'fb'..."
4219,2021-08-18,00:54:48,finapse_24_7,[Last 24 Hours] Stocks trending among elite #...,"['fintwit', 'investing', 'stocks', 'wallstreet...","['vrpx', 'tsla', 'se', 'amzn', 'aapl', 'mrna',..."
4220,2021-08-18,00:13:05,multibaggeranil,@TomGardnerFool $AMZN $GOOGL $NOW $FB $TEAM ...,[],"['amzn', 'googl', 'now', 'fb', 'team', 'zi', '..."
4221,2021-08-18,00:03:02,stckpro,$AAPL $ABBV $AMZN NEW ARTICLE : Tracking Warre...,[],"['aapl', 'abbv', 'amzn', 'aapl']"

In [10]:
# date_format = '%m/%d/%y'
# new_AMZN_data_df = input('date:')
# new_AMZN_data_df = datetime.strptime(new_AMZN_data_df,date_format)

# if (datetime.strptime("8/20/2021", date_format) <= new_AMZN_data_df < datetime.strptime("8/18/2021", date_format)):

In [11]:
new_AMZN_data_df.to_csv('./cleaned_data/AMZN_clean_data.csv')
new_GOOG_data_df.to_csv('./cleaned_data/GOOG_clean_data.csv')
new_JNJ_data_df.to_csv('./cleaned_data/JNJ_clean_data.csv')
new_PFE_data_df.to_csv('./cleaned_data/PFE_clean_data.csv')
new_TSLA_data_df.to_csv('./cleaned_data/TSLA_clean_data.csv')
new_MRNA_data_df.to_csv('./cleaned_data/MRNA_clean_data.csv')